### ISSUE TITLE
China disappearing from the data?

### ISSUE THREAD

**Issue by GaelVaroquaux** [sudharshan-ashok/pycovid#2]
Hi, thanks for the package!

I think that you have an alignment problem: upstream has renamed China and the merge with the iso code is failing. Indeed, in https://raw.githubusercontent.com/RamiKrispin/coronavirus-csv/master/coronavirus_dataset.csv and in https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/slim-3/slim-3.csv "China" is called "China". But in pycovid https://github.com/sudharshan-ashok/pycovid/blob/master/pycovid/pycovid.py#L25, "China" is renamed to "Mainland China".

**Comment by kylemath** [comment]
also fixed in https://github.com/sudharshan-ashok/pycovid/pull/5

**Comment by sudharshan-ashok** [comment]
Resolved!

**Comment by GaelVaroquaux** [comment]
Thanks!!!
