### ISSUE TITLE
Features for provinces and states 

### ISSUE THREAD

**Issue by kylemath** [sudharshan-ashok/pycovid#4]
I am working on features for plotting changes over time in provinces, starting with canada, here: 
https://github.com/kylemath/pycovid
<img width="2051" alt="Screen Shot 2020-03-14 at 3 28 57 PM" src="https://user-images.githubusercontent.com/3662613/76690902-1fefd300-6602-11ea-9fd3-3b088c78e71d.png">

**Comment by kylemath** [comment]
created a pull request here: 
https://github.com/sudharshan-ashok/pycovid/pull/5

**Comment by sudharshan-ashok** [comment]
Great visualization Kyle! Thank you

Merged into master
